
name: Auto Deployment
on:
  push: 
    branches: [ feat-auto-deployment ]

jobs:
  build-production:
    name: Build production
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build
    
    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AUTO_DEPLOYMENT_SSH_HOST }}
        username: ${{ secrets.AUTO_DEPLOYMENT_USERNAME }}
        port: '22'
        key: ${{ secrets.AUTO_DEPLOYMENT_SSH_KEY }}
        source: "./.next/*"
        target: "/home/ubuntu/website"
        rm: true

    - name: Restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AUTO_DEPLOYMENT_SSH_HOST }}
        username: ${{ secrets.AUTO_DEPLOYMENT_USERNAME }}
        key: ${{ secrets.AUTO_DEPLOYMENT_SSH_KEY }}
        script: |
          cd /home/ubuntu/website
          sudo pm2 ls
          